### ISSUE TITLE
Class not found : com.oracle.truffle.sl.nodes.interop.SLForeignToSLTypeNodeGen;

### ISSUE THREAD

**Issue by killme2008** [graalvm/simplelanguage#22]
The class `SLForeignToSLTypeNodeGen` is not exists, even in latest version 0.27, how can it fix it?

**Comment by dougxc** [comment]
simplelanguage is now integrated into the graal repo and you can find this file there: https://github.com/graalvm/graal/blob/3b1d7f2e9c3bb6a57600dbbcad20e5ecea36a20f/truffle/src/com.oracle.truffle.sl/src/com/oracle/truffle/sl/nodes/interop/SLForeignToSLTypeNode.java#L59

**Comment by killme2008** [comment]
Hi, thanks.

But `SLForeignToSLTypeNode` is not `SLForeignToSLTypeNodeGen`, any way to generate the later class?

**Comment by dougxc** [comment]
As implied by the name, it's a generated file (generated by a Truffle annotation processor).

**Comment by killme2008** [comment]
ok, thanks a lot.
